// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('app.board.ctrls', []).controller('BoardCtrl', ['$scope', '$window']);

}).call(this);

//# sourceMappingURL=BoardCtrl.map
