// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('app.login.ctrls', []).controller('LoginCtrl', ['$scope', '$window']);

}).call(this);

//# sourceMappingURL=LoginCtrl.map
